#!/usr/bin/env python3
"""Compile a small ENIGMA PTSD/MDD convergence table from verified sources.

This table is intended as clinical-background context only. ENIGMA case-control
morphometry findings do not directly measure stimulus multivalence, vmPFC/ACC
afferent architecture, or the causal circuit properties tested in the mouse
experiments, so they should not be treated as quantitative validation of the
mouse connectomic, CORT, or ketamine results.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    default_output = Path(__file__).resolve().parent / "enigma_convergence_table.csv"
    parser = argparse.ArgumentParser(
        description="Build a CSV of verified ENIGMA PTSD/MDD summary statistics."
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=default_output,
        help="Output CSV path.",
    )
    return parser.parse_args()


def build_rows() -> list[dict[str, str | float]]:
    """Return curated rows with directly verified summary statistics."""

    return [
        {
            "disorder_group": "PTSD",
            "region": "Hippocampus",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in current PTSD vs trauma-exposed controls",
            "effect_size": -0.17,
            "effect_size_metric": "Cohen's d",
            "sample_size": "794 PTSD / 1074 trauma-exposed controls (total 1868)",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pubmed.ncbi.nlm.nih.gov/29217296/",
            "notes": "Largest ENIGMA/PGC PTSD subcortical meta-analysis in the abstract.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Amygdala",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in current PTSD vs trauma-exposed controls",
            "effect_size": -0.11,
            "effect_size_metric": "Cohen's d",
            "sample_size": "794 PTSD / 1074 trauma-exposed controls (total 1868)",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pubmed.ncbi.nlm.nih.gov/29217296/",
            "notes": "Abstract notes the amygdala result did not survive Bonferroni correction.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right lateral orbitofrontal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.111,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1259 PTSD / 2079 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Value verified from Table 2 of the open full text.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left lateral orbitofrontal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.107,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1265 PTSD / 2089 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Value verified from Table 2 of the open full text.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left caudal anterior cingulate cortex",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.098,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1266 PTSD / 2090 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Value verified from Table 2 of the open full text.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left rostral anterior cingulate cortex",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.074,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1258 PTSD / 2090 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Value verified from Table 2 of the open full text.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Tapetum (corpus callosum)",
            "modality": "white matter",
            "measure": "fractional anisotropy",
            "direction_of_effect": "lower FA in PTSD vs controls",
            "effect_size": -0.11,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1426 PTSD / 1621 controls (total 3047)",
            "source_citation": "Dennis et al. 2021, Mol Psychiatry, doi:10.1038/s41380-019-0631-x",
            "source_url": "https://pubmed.ncbi.nlm.nih.gov/31857689/",
            "notes": "Abstract emphasizes hippocampal interhemispheric white-matter relevance.",
        },
        {
            "disorder_group": "MDD",
            "region": "Hippocampus",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in MDD vs healthy controls",
            "effect_size": -0.14,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1728 MDD / 7199 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pubmed.ncbi.nlm.nih.gov/26122586/",
            "notes": "Abstract notes stronger effects in recurrent and early-onset MDD.",
        },
        {
            "disorder_group": "MDD",
            "region": "Left medial orbitofrontal cortex",
            "modality": "cortical thickness",
            "measure": "regional cortical thickness",
            "direction_of_effect": "thinner cortex in adult MDD vs controls",
            "effect_size": -0.134,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1902 adult MDD / 7658 controls",
            "source_citation": "Schmaal et al. 2017, Mol Psychiatry, doi:10.1038/mp.2016.60",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5444023/",
            "notes": "Value verified from open full text Table 1; abstract adult sample size used.",
        },
        {
            "disorder_group": "MDD",
            "region": "Left rostral anterior cingulate cortex",
            "modality": "cortical thickness",
            "measure": "regional cortical thickness",
            "direction_of_effect": "thinner cortex in adult MDD vs controls",
            "effect_size": -0.130,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1896 adult MDD / 7628 controls",
            "source_citation": "Schmaal et al. 2017, Mol Psychiatry, doi:10.1038/mp.2016.60",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5444023/",
            "notes": "Value verified from open full text Table 1.",
        },
        {
            "disorder_group": "MDD",
            "region": "Right rostral anterior cingulate cortex",
            "modality": "cortical thickness",
            "measure": "regional cortical thickness",
            "direction_of_effect": "thinner cortex in adult MDD vs controls",
            "effect_size": -0.098,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1900 adult MDD / 7654 controls",
            "source_citation": "Schmaal et al. 2017, Mol Psychiatry, doi:10.1038/mp.2016.60",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5444023/",
            "notes": "Value verified from open full text Table 1.",
        },
        # --- Expanded rows below (added 2024, all from the same 4 already-verified
        # papers above; every value independently re-verified against fresh PMC XML
        # fetches by a second agent before being added, per repo anti-fabrication
        # protocol). Schmaal 2016 Table 1 non-significant subcortical structures: ---
        {
            "disorder_group": "MDD",
            "region": "Lateral ventricles",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "larger in MDD vs controls (not significant)",
            "effect_size": 0.056,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1689 MDD / 7058 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.130, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Thalamus",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in MDD vs controls (not significant)",
            "effect_size": -0.044,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1682 MDD / 7046 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.250, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Caudate",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in MDD vs controls (not significant)",
            "effect_size": -0.023,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1681 MDD / 7034 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.641, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Putamen",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "larger in MDD vs controls (not significant)",
            "effect_size": 0.012,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1656 MDD / 6957 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.722, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Pallidum",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in MDD vs controls (not significant; near zero)",
            "effect_size": -0.001,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1657 MDD / 7018 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.972, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Amygdala",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in MDD vs controls (not significant)",
            "effect_size": -0.06,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1696 MDD / 7060 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.097, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Accumbens",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in MDD vs controls (not significant)",
            "effect_size": -0.019,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1652 MDD / 6967 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": "Table 1, verbatim XML; p=0.569, n.s.",
        },
        {
            "disorder_group": "MDD",
            "region": "Intracranial volume (ICV)",
            "modality": "structural volume",
            "measure": "intracranial volume",
            "direction_of_effect": "smaller in MDD vs controls (not significant)",
            "effect_size": -0.029,
            "effect_size_metric": "Cohen's d",
            "sample_size": "1728 MDD / 7199 controls",
            "source_citation": "Schmaal et al. 2016, Mol Psychiatry, doi:10.1038/mp.2015.69",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4879183/",
            "notes": (
                "Table 1, verbatim XML; p=0.575, n.s. Not a brain region per se; "
                "adjustment covariate."
            ),
        },
        # Logue 2018 Table 1 non-significant subcortical structures (PTSD vs ALL
        # controls comparison -- distinct N from the existing hippocampus/amygdala
        # rows above, which use the PTSD-vs-trauma-exposed-controls subgroup):
        {
            "disorder_group": "PTSD",
            "region": "Nucleus accumbens",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in PTSD vs all controls (not significant)",
            "effect_size": -0.081,
            "effect_size_metric": "Cohen's d",
            "sample_size": "778 PTSD / 1061 controls",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5951719/",
            "notes": "Table 1, verbatim XML; p=.20, n.s.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Caudate",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "larger in PTSD vs all controls (not significant; near zero)",
            "effect_size": 0.0064,
            "effect_size_metric": "Cohen's d",
            "sample_size": "780 PTSD / 1063 controls",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5951719/",
            "notes": "Table 1, verbatim XML; p=.91, n.s.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Lateral ventricle",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "larger in PTSD vs all controls (not significant)",
            "effect_size": 0.084,
            "effect_size_metric": "Cohen's d",
            "sample_size": "781 PTSD / 1064 controls",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5951719/",
            "notes": "Table 1, verbatim XML; p=.089, n.s., bilateral mean.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Pallidum",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "larger in PTSD vs all controls (not significant)",
            "effect_size": 0.047,
            "effect_size_metric": "Cohen's d",
            "sample_size": "766 PTSD / 1048 controls",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5951719/",
            "notes": "Table 1, verbatim XML; p=.34, n.s.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Putamen",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "larger in PTSD vs all controls (not significant; near zero)",
            "effect_size": 0.016,
            "effect_size_metric": "Cohen's d",
            "sample_size": "764 PTSD / 1050 controls",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5951719/",
            "notes": "Table 1, verbatim XML; p=.75, n.s.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Thalamus",
            "modality": "structural volume",
            "measure": "subcortical volume",
            "direction_of_effect": "smaller in PTSD vs all controls (not significant)",
            "effect_size": -0.039,
            "effect_size_metric": "Cohen's d",
            "sample_size": "772 PTSD / 1053 controls",
            "source_citation": "Logue et al. 2018, Biol Psychiatry, doi:10.1016/j.biopsych.2017.09.006",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5951719/",
            "notes": "Table 1, verbatim XML; p=.43, n.s.",
        },
        # Wang 2021 Table 2 additional FDR-significant cortical volume regions:
        {
            "disorder_group": "PTSD",
            "region": "Right medial orbitofrontal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.067,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1232 PTSD / 2071 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.039.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right pars orbitalis (inferior frontal gyrus)",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.086,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1269 PTSD / 2092 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.020.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right superior frontal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.082,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1211 PTSD / 2017 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.008.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left medial orbitofrontal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.068,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1250 PTSD / 2082 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.038.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left rostral middle frontal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.062,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1256 PTSD / 2081 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.039.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right insular gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.073,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1118 PTSD / 1880 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.039.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left insular gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.066,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1197 PTSD / 2014 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.036.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left posterior cingulate cortex",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.078,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1270 PTSD / 2095 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.039.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right superior temporal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.081,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1209 PTSD / 2035 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.021.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right middle temporal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.075,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1249 PTSD / 2074 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.020.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left superior temporal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.089,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1207 PTSD / 1989 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.018.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left banks of superior temporal sulcus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.084,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1122 PTSD / 1879 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.039.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right precuneus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.065,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1258 PTSD / 2091 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.038.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right superior parietal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.068,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1153 PTSD / 1974 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.039.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right inferior parietal gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.065,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1239 PTSD / 2066 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.041.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Left precuneus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.061,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1263 PTSD / 2093 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.041.",
        },
        {
            "disorder_group": "PTSD",
            "region": "Right lingual gyrus",
            "modality": "cortical volume",
            "measure": "regional cortical volume",
            "direction_of_effect": "smaller in PTSD vs controls",
            "effect_size": -0.11,
            "effect_size_metric": "standardized coefficient",
            "sample_size": "1186 PTSD / 1973 controls",
            "source_citation": "Wang et al. 2021, Mol Psychiatry, doi:10.1038/s41380-020-00967-1",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180531/",
            "notes": "Table 2, verbatim XML; FDR q=0.006.",
        },
    ]


def main() -> None:
    """Write the ENIGMA convergence CSV."""

    args = parse_args()
    args.output_csv.parent.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(build_rows()).sort_values(
        ["disorder_group", "modality", "region"], ignore_index=True
    )
    df.to_csv(args.output_csv, index=False)
    print(f"Wrote ENIGMA convergence table to: {args.output_csv}")


if __name__ == "__main__":
    main()
